//
//  CategoryViewModel.swift
//  HealthMini
//
//  Created by Mattia De Franco on 22/11/23.
//

import SwiftUI
import Foundation

class CategoryViewModel: ObservableObject {
    @Published var searchText  : String = ""
    @Published var category = [
        Category(name: "Activity", image: "flame.fill",color: .red, subcategories:[
            Subcategory(name: "Active Energy",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), dati: "90", unit:"kcal"),
            Subcategory(name: "Activity",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Cycling Cadence",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Cycling Distance",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Cycling Functionale Threshold Power",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Cycling Power",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Cycling Speed",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Downhill Snow Sports Distance",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Exercise Minutes",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Flights Climbed",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Move Minutes",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "NikeFuel",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Physical Effort",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Pushes",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Resting Energy",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Running Power",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Running Speed",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Stand Hours",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Stand Minutes",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Steps",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Swimming Distance",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Swiming Strokes",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Underwater Depth",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Walking + Running Distance",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Wheelchair Distance",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
            Subcategory(name: "Workouts",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
               ]),
        Category(name: "Body Measurements", image:"figure", color: .purple, subcategories: [
            Subcategory(name: "Body Fat Percentage", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Body Mass Index", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Electrodermal Activity", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Height", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Lean Body Mass", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Vision Prescription", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Height", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Waist Circumference", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Weight", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Wrist Temperature", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
              ]),
        Category(name: "Cycle Tracking", image:"circle.hexagonpath", color: .purple, subcategories: [
            Subcategory(name: "Basal Body Temperature", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Cervical Mucus Quality", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Contraceptives", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Infrequent Periods", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Irregular Cycles", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Lactation", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Menstruation", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Ovulation Test Result", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Persistent Spotting", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Pregrancy", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Pregrancy Test Result", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Progesterone Test Result", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Prolonged Periods", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Sexual Activity", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
            Subcategory(name: "Spotting", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
               ]),//different
        Category(name: "Hearing", image:"ear", color: .blue, subcategories: [
            Subcategory(name: "Audiogram", image:"ear", color: Color(red: 58 / 255.0, green: 130 / 255.0, blue: 247 / 255.0)),
            Subcategory(name: "Environmental Sound Levels", image:"ear", color: Color(red: 58 / 255.0, green: 130 / 255.0, blue: 247 / 255.0)),
            Subcategory(name: "Environmental Sound Reduction", image:"ear", color: Color(red: 58 / 255.0, green: 130 / 255.0, blue: 247 / 255.0)),
            Subcategory(name: "Headphones Audio Levels", image:"ear", color: Color(red: 58 / 255.0, green: 130 / 255.0, blue: 247 / 255.0)),
            Subcategory(name: "Headphones Notifications", image:"ear", color: Color(red: 58 / 255.0, green: 130 / 255.0, blue: 247 / 255.0)),
            Subcategory(name: "Noise Notifications", image:"ear", color: Color(red: 58 / 255.0, green: 130 / 255.0, blue: 247 / 255.0)),
        ] ),
        Category(name: "Heart", image:"heart.fill", color: .red, subcategories: [
            Subcategory(name: "AF History", image:"heart.fill", color: .red),
            Subcategory(name: "Blood Pressure", image:"heart.fill", color: .red),
            Subcategory(name: "Cardio Fitness", image:"heart.fill", color: .red),
            Subcategory(name: "Cardio Fitness Notifications", image:"heart.fill", color: .red),
            Subcategory(name: "Cardio Recovery", image:"heart.fill", color: .red),
            Subcategory(name: "Electrocardiograms (ECG)", image:"heart.fill", color: .red),
            Subcategory(name: "Heart Rate", image:"heart.fill", color: .red),
            Subcategory(name: "Heart Rate Variability", image:"heart.fill", color: .red),
            Subcategory(name: "High Heart Rate Notifications", image:"heart.fill", color: .red),
            Subcategory(name: "Irregular Rhythm Notifications", image:"heart.fill", color: .red),
            Subcategory(name: "Low Heart Rate Notifications", image:"heart.fill", color: .red),
            Subcategory(name: "Peripheral Perfusion Index", image:"heart.fill", color: .red),
            Subcategory(name: "Resting Heart Rate", image:"heart.fill", color: .red),
            Subcategory(name: "Walking Heart Rate Average", image:"heart.fill", color: .red),
        ]),
        Category(name: "Medications", image:"pills.fill", color: .blue, subcategories: [ 
            Subcategory(name: "Medications", image:"pills.fill", color: .blue),
        ]),
        Category(name: "Mental Well Being", image:"brain.head.profile", color: .cyan, subcategories: [
            Subcategory(name: "Anxiety Risk", image:"brain.head.profile", color: .cyan),
            Subcategory(name: "Depression Risk", image:"brain.head.profile", color: .cyan),
            Subcategory(name: "Mindful Minutes", image:"brain.head.profile", color: .cyan),
            Subcategory(name: "State of Mind", image:"brain.head.profile", color: .cyan),
        ]),
        Category(name: "Mobility", image:"arrow", color: .yellow, subcategories: [
            Subcategory(name: "Double Support Time", image:"arrow", color: .yellow),
 Subcategory(name: "Ground Contact Time", image:"arrow", color: .yellow),
Subcategory(name: "Running Stride Lenght", image:"arrow", color: .yellow),
Subcategory(name: "Six-Minute Walk", image:"arrow", color: .yellow),
Subcategory(name: "Stair Speed: Down", image:"arrow", color: .yellow),
Subcategory(name: "Stair Speed: Up", image:"arrow", color: .yellow),
Subcategory(name: "Vertical Oscillation", image:"arrow", color: .yellow),
Subcategory(name: "Walking Asymmetry", image:"arrow", color: .yellow),
Subcategory(name: "Walking Speed", image:"arrow", color: .yellow),
Subcategory(name: "Walking Steadiness", image:"arrow", color: .yellow),
Subcategory(name: "Walking Steadiness Notifications", image:"arrow", color: .yellow),
Subcategory(name: "Walking Step Lenght", image:"arrow", color: .yellow),]),//different
        Category(name: "Nutrition", image:"mela", color: .green, subcategories: [
            Subcategory(name: "Biotin", image:"mela", color: .green),
            Subcategory(name: "Caffeine", image:"mela", color: .green),
            Subcategory(name: "Calcium", image:"mela", color: .green),
            Subcategory(name: "Carbohydrates", image:"mela", color: .green),
            Subcategory(name: "Chloride", image:"mela", color: .green),
                                                                                Subcategory(name: "Chromium", image:"mela", color: .green),
                                                                                Subcategory(name: "Copper", image:"mela", color: .green),
                                                                                Subcategory(name: "Dietary Cholesterol", image:"mela", color: .green),
                                                                                Subcategory(name: "Dietary Energy", image:"mela", color: .green),
                                                                                Subcategory(name: "Dietary Sugar", image:"mela", color: .green),
                                                                                Subcategory(name: "Fibre", image:"mela", color: .green),
                                                                                Subcategory(name: "Folate", image:"mela", color: .green),
                                                                                Subcategory(name: "Iodine", image:"mela", color: .green),
                                                                                Subcategory(name: "Iron", image:"mela", color: .green),
                                                                                Subcategory(name: "Magnesium", image:"mela", color: .green),
                                                                                Subcategory(name: "Manganese", image:"mela", color: .green),
                                                                                Subcategory(name: "Molybdenum", image:"mela", color: .green),
                                                                                Subcategory(name: "Monounsaturated Fat", image:"mela", color: .green),
                                                                                Subcategory(name: "Niacin", image:"mela", color: .green),
                                                                                Subcategory(name: "Panthothenic Acid", image:"mela", color: .green),
                                                                                Subcategory(name: "Phosphorus", image:"mela", color: .green),
                                                                                Subcategory(name: "Polynsaturated Fat", image:"mela", color: .green),
                                                                                Subcategory(name: "Potassium", image:"mela", color: .green),
                                                                                Subcategory(name: "Protein", image:"mela", color: .green),
                                                                                Subcategory(name: "Riboflavin", image:"mela", color: .green),
                                                                                Subcategory(name: "Staurated Fat", image:"mela", color: .green),
                                                                                Subcategory(name: "Selenium", image:"mela", color: .green),
                                                                                Subcategory(name: "Sodium", image:"mela", color: .green),
                                                                                Subcategory(name: "Thiamine", image:"mela", color: .green),
                                                                                Subcategory(name: "Total Fat", image:"mela", color: .green),
                                                                                Subcategory(name: "Vitamin A", image:"mela", color: .green),
                                                                                Subcategory(name: "Vitamin B6", image:"mela", color: .green),
                                                                                Subcategory(name: "Vitamin B12", image:"mela", color: .green),
                                                                                Subcategory(name: "Vitamin C", image:"mela", color: .green),
                                                                                Subcategory(name: "Vitamin D", image:"mela", color: .green),
                                                                                Subcategory(name: "Vitamin E", image:"mela", color: .green),
                                                                                Subcategory(name: "Vitamin K", image:"mela", color: .green),
                                                                                Subcategory(name: "Water", image:"mela", color: .green),
                                                                                Subcategory(name: "Zinc", image:"mela", color: .green),]),//different
        Category(name: "Respiratory", image:"lungs.fill", color: .mint, subcategories: [
            Subcategory(name: "Blood Oxigen", image:"lungs.fill", color: .mint),
            Subcategory(name: "Forced Expiratory Volume, 1 sec", image:"lungs.fill", color: .mint),
            Subcategory(name: "Forced Vital Capacity", image:"lungs.fill", color: .mint),
            Subcategory(name: "Inhaler Usage", image:"lungs.fill", color: .mint),
            Subcategory(name: "Peak Expiratory Flow Rate", image:"lungs.fill", color: .mint),
            Subcategory(name: "Respiratory Rate", image:"lungs.fill", color: .mint),]),
        Category(name: "Sleep", image:"bed.double.fill", color: .mint, subcategories: [ Subcategory(name: "Sleep", image:"bed.double.fill", color: .mint),]),
        Category(name: "Symptoms", image:"list.clipboard", color: .purple, subcategories: [ Subcategory(name: "Abdominal Cramps", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Acne", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Appetite Changes", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Bladder Incontinence", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Bloating", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Body and Muscle Ache", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Breast Pain", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Chest Tightness or Pain", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Chills", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Congestion", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Constipation", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Coughing", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Diarrhoea", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Dizziness", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Dry Skin", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Fainting", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Fatigue", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Fever", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Hair Loss", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Headache", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Heathburn", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Hot Flushes", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Loss of Smell", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Loss of Taste", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Lower Back Pain", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Memory Lapse", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Mood Changes", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Nausea", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Night Sweats", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Pelvic Pain", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Rapid, Pounding or fluttering Hertbeat", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Runny Nose", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Shortness of Breath", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Skipped Heartbeat", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Sleep Changes", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Sore Throat", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "VAginale Dryness", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Vomiting", image:"list.clipboard", color: .purple),
                                                                                     Subcategory(name: "Wheezing", image:"list.clipboard", color: .purple),]),//different color
        Category(name: "Vitals", image:"waveform.path.ecg.rectangle", color: .pink, subcategories: [ 
            Subcategory(name: "Blood Glucose", image:"waveform.path.ecg.rectangle", color: .pink),
            Subcategory(name: "Body Temperature", image:"waveform.path.ecg.rectangle", color: .pink),]),//different colors
        Category(name: "Other Data", image:"cross.fill", color: .blue, subcategories: [
            Subcategory(name: "Alcohol Consuptions", image:"cross.fill", color: .blue),
                                                                                Subcategory(name: "Blood Alcohol COntent", image:"cross.fill", color: .blue),
                                                                                Subcategory(name: "Handwashing", image:"cross.fill", color: .blue),
                                                                                Subcategory(name: "Insulin Delivery", image:"cross.fill", color: .blue),
                                                                                Subcategory(name: "Number of Times Fallen", image:"cross.fill", color: .blue),
                                                                                Subcategory(name: "Time in Daylight", image:"cross.fill", color: .blue),
                                                                                Subcategory(name: "Toothbrushing", image:"cross.fill", color: .blue),
                                                                                Subcategory(name: "Uv INdex", image:"cross.fill", color: .blue),
                                                                                Subcategory(name: "Water Temperature", image:"cross.fill", color: .blue),]),//different
        Category(name: "Clinical Documents", image:"list.clipboard", color: .blue, subcategories: [
            Subcategory(name: "Clinical Documents", image: "list.clipboard", color:.blue)]),//different colors
    ]
}

