//
//  SubCategortViewModel.swift
//  HealthMini
//
//  Created by Mattia De Franco on 22/11/23.
//


import Foundation
import SwiftUI

class SubCategoryViewModel{
 var subcategories = [
        
        Subcategory(name: "Active Energy",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), dati: "340", unit:"kcal"),
        Subcategory(name: "Activity",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Cycling Cadence",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Cycling Distance",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Cycling Functionale Threshold Power",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Cycling Power",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Cycling Speed",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Downhill Snow Sports Distance",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Exercise Minutes",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Flights Climbed",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"floors"),
        Subcategory(name: "Move Minutes",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "NikeFuel",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Physical Effort",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Pushes",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Resting Energy",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), dati: "1930",unit:"kcal"),
        Subcategory(name: "Running Power",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Running Speed",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Stand Hours",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Stand Minutes",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Steps",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), dati:"6770", unit:"steps"),
        Subcategory(name: "Swimming Distance",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Swiming Strokes",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Underwater Depth",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Walking + Running Distance",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19),dati:"4,8", unit:"km"),
        Subcategory(name: "Wheelchair Distance",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
        Subcategory(name: "Workouts",image: "flame.fill",color: Color(red: 0.93, green: 0.39, blue: 0.19), unit:"kcal"),
           
        Subcategory(name: "Body Fat Percentage", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Body Mass Index", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Electrodermal Activity", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Height", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Lean Body Mass", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Vision Prescription", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Height", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0), dati: "185", unit:"cm"),
        Subcategory(name: "Waist Circumference", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Weight", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0), dati: "80", unit:"kg"),
        Subcategory(name: "Wrist Temperature", image:"figure", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
          
        Subcategory(name: "Basal Body Temperature", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Cervical Mucus Quality", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Contraceptives", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Infrequent Periods", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Irregular Cycles", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Lactation", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Menstruation", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Ovulation Test Result", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Persistent Spotting", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Pregrancy", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Pregrancy Test Result", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Progesterone Test Result", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Prolonged Periods", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Sexual Activity", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
        Subcategory(name: "Spotting", image:"circle.hexagonpath", color: Color(red: 178 / 255.0, green: 95 / 255.0, blue: 234 / 255.0)),
          
        Subcategory(name: "Audiogram", image:"ear", color: Color(red: 58 / 255.0, green: 130 / 255.0, blue: 247 / 255.0)),
        Subcategory(name: "Environmental Sound Levels", image:"ear", color: Color(red: 58 / 255.0, green: 130 / 255.0, blue: 247 / 255.0)),
        Subcategory(name: "Environmental Sound Reduction", image:"ear", color: Color(red: 58 / 255.0, green: 130 / 255.0, blue: 247 / 255.0)),
        Subcategory(name: "Headphones Audio Levels", image:"ear", color: Color(red: 58 / 255.0, green: 130 / 255.0, blue: 247 / 255.0)),
        Subcategory(name: "Headphones Notifications", image:"ear", color: Color(red: 58 / 255.0, green: 130 / 255.0, blue: 247 / 255.0)),
        Subcategory(name: "Noise Notifications", image:"ear", color: Color(red: 58 / 255.0, green: 130 / 255.0, blue: 247 / 255.0)),
           
        Subcategory(name: "AF History", image:"heart.fill", color: .red),
        Subcategory(name: "Blood Pressure", image:"heart.fill", color: .red),
        Subcategory(name: "Cardio Fitness", image:"heart.fill", color: .red),
        Subcategory(name: "Cardio Fitness Notifications", image:"heart.fill", color: .red),
        Subcategory(name: "Cardio Recovery", image:"heart.fill", color: .red),
        Subcategory(name: "Electrocardiograms (ECG)", image:"heart.fill", color: .red),
        Subcategory(name: "Heart Rate", image:"heart.fill", color: .red),
        Subcategory(name: "Heart Rate Variability", image:"heart.fill", color: .red),
        Subcategory(name: "High Heart Rate Notifications", image:"heart.fill", color: .red),
        Subcategory(name: "Irregular Rhythm Notifications", image:"heart.fill", color: .red),
        Subcategory(name: "Low Heart Rate Notifications", image:"heart.fill", color: .red),
        Subcategory(name: "Peripheral Perfusion Index", image:"heart.fill", color: .red),
        Subcategory(name: "Resting Heart Rate", image:"heart.fill", color: .red),
        Subcategory(name: "Walking Heart Rate Average", image:"heart.fill", color: .red),
           
        Subcategory(name: "Medications", image:"pills.fill", color: Color(red: 0.56, green: 0.56, blue: 0.58)),
          
        Subcategory(name: "Anxiety Risk", image:"brain.head.profile", color: Color(red: 135 / 255.0, green: 227 / 255.0, blue: 225 / 255.0)),
        Subcategory(name: "Depression Risk", image:"brain.head.profile", color: Color(red: 135 / 255.0, green: 227 / 255.0, blue: 225 / 255.0)),
        Subcategory(name: "Mindful Minutes", image:"brain.head.profile", color: Color(red: 135 / 255.0, green: 227 / 255.0, blue: 225 / 255.0)),
        Subcategory(name: "State of Mind", image:"brain.head.profile", color: Color(red: 135 / 255.0, green: 227 / 255.0, blue: 225 / 255.0)),
          
        Subcategory(name: "Double Support Time", image:"arrow", color: Color(red: 241 / 255.0, green: 163 / 255.0, blue: 59 / 255.0)),
        Subcategory(name: "Ground Contact Time", image:"arrow", color: Color(red: 241 / 255.0, green: 163 / 255.0, blue: 59 / 255.0)),
        Subcategory(name: "Running Stride Lenght", image:"arrow", color: Color(red: 241 / 255.0, green: 163 / 255.0, blue: 59 / 255.0)),
        Subcategory(name: "Six-Minute Walk", image:"arrow", color: Color(red: 241 / 255.0, green: 163 / 255.0, blue: 59 / 255.0)),
        Subcategory(name: "Stair Speed: Down", image:"arrow", color: Color(red: 241 / 255.0, green: 163 / 255.0, blue: 59 / 255.0)),
        Subcategory(name: "Stair Speed: Up", image:"arrow", color: Color(red: 241 / 255.0, green: 163 / 255.0, blue: 59 / 255.0)),
        Subcategory(name: "Vertical Oscillation", image:"arrow", color: Color(red: 241 / 255.0, green: 163 / 255.0, blue: 59 / 255.0)),
        Subcategory(name: "Walking Asymmetry", image:"arrow", color: Color(red: 241 / 255.0, green: 163 / 255.0, blue: 59 / 255.0)),
        Subcategory(name: "Walking Speed", image:"arrow", color: Color(red: 241 / 255.0, green: 163 / 255.0, blue: 59 / 255.0)),
        Subcategory(name: "Walking Steadiness", image:"arrow", color: Color(red: 241 / 255.0, green: 163 / 255.0, blue: 59 / 255.0)),
        Subcategory(name: "Walking Steadiness Notifications", image:"arrow", color: Color(red: 241 / 255.0, green: 163 / 255.0, blue: 59 / 255.0)),
        Subcategory(name: "Walking Step Lenght", image:"arrow", color: Color(red: 241 / 255.0, green: 163 / 255.0, blue: 59 / 255.0)),
           
        Subcategory(name: "Biotin", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Caffeine", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Calcium", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Carbohydrates", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Chloride", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Chromium", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Copper", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Dietary Cholesterol", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Dietary Energy", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Dietary Sugar", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Fibre", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Folate", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Iodine", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Iron", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Magnesium", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Manganese", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Molybdenum", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Monounsaturated Fat", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Niacin", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Panthothenic Acid", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Phosphorus", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Polynsaturated Fat", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Potassium", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Protein", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Riboflavin", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Staurated Fat", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Selenium", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Sodium", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Thiamine", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Total Fat", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Vitamin A", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Vitamin B6", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Vitamin B12", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Vitamin C", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Vitamin D", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Vitamin E", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Vitamin K", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Water", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
        Subcategory(name: "Zinc", image:"mela", color: Color(red: 103 / 255.0, green: 206 / 255.0, blue: 103 / 255.0)),
          
        Subcategory(name: "Alcohol Consuptions", image:"cross.fill", color: .blue),
        Subcategory(name: "Blood Alcohol COntent", image:"cross.fill", color: .blue),
        Subcategory(name: "Handwashing", image:"cross.fill", color: .blue),
        Subcategory(name: "Insulin Delivery", image:"cross.fill", color: .blue),
        Subcategory(name: "Number of Times Fallen", image:"cross.fill", color: .blue),
        Subcategory(name: "Time in Daylight", image:"cross.fill", color: .blue),
        Subcategory(name: "Toothbrushing", image:"cross.fill", color: .blue),
        Subcategory(name: "Uv INdex", image:"cross.fill", color: .blue),
        Subcategory(name: "Water Temperature", image:"cross.fill", color: .blue),
          
        Subcategory(name: "Blood Oxigen", image:"lungs.fill", color: Color(red: 0.56, green: 0.56, blue: 0.58)),
        Subcategory(name: "Forced Expiratory Volume, 1 sec", image:"lungs.fill", color: Color(red: 0.56, green: 0.56, blue: 0.58)),
        Subcategory(name: "Forced Vital Capacity", image:"lungs.fill", color: Color(red: 0.56, green: 0.56, blue: 0.58)),
        Subcategory(name: "Inhaler Usage", image:"lungs.fill", color: Color(red: 0.56, green: 0.56, blue: 0.58)),
        Subcategory(name: "Peak Expiratory Flow Rate", image:"lungs.fill", color: Color(red: 0.56, green: 0.56, blue: 0.58)),
        Subcategory(name: "Respiratory Rate", image:"lungs.fill", color: Color(red: 0.56, green: 0.56, blue: 0.58)),
           
        Subcategory(name: "Sleep", image:"bed.double.fill", color: Color(red: 135 / 255.0, green: 227 / 255.0, blue: 225 / 255.0), dati: "8", unit:"hr"),
           
        Subcategory(name: "Abdominal Cramps", image:"list.clipboard", color: .purple),
        Subcategory(name: "Acne", image:"list.clipboard", color: .purple),
        Subcategory(name: "Appetite Changes", image:"list.clipboard", color: .purple),
        Subcategory(name: "Bladder Incontinence", image:"list.clipboard", color: .purple),
        Subcategory(name: "Bloating", image:"list.clipboard", color: .purple),
        Subcategory(name: "Body and Muscle Ache", image:"list.clipboard", color: .purple),
        Subcategory(name: "Breast Pain", image:"list.clipboard", color: .purple),
        Subcategory(name: "Chest Tightness or Pain", image:"list.clipboard", color: .purple),
        Subcategory(name: "Chills", image:"list.clipboard", color: .purple),
        Subcategory(name: "Congestion", image:"list.clipboard", color: .purple),
        Subcategory(name: "Constipation", image:"list.clipboard", color: .purple),
        Subcategory(name: "Coughing", image:"list.clipboard", color: .purple),
        Subcategory(name: "Diarrhoea", image:"list.clipboard", color: .purple),
        Subcategory(name: "Dizziness", image:"list.clipboard", color: .purple),
        Subcategory(name: "Dry Skin", image:"list.clipboard", color: .purple),
        Subcategory(name: "Fainting", image:"list.clipboard", color: .purple),
        Subcategory(name: "Fatigue", image:"list.clipboard", color: .purple),
        Subcategory(name: "Fever", image:"list.clipboard", color: .purple),
        Subcategory(name: "Hair Loss", image:"list.clipboard", color: .purple),
        Subcategory(name: "Headache", image:"list.clipboard", color: .purple),
        Subcategory(name: "Heathburn", image:"list.clipboard", color: .purple),
        Subcategory(name: "Hot Flushes", image:"list.clipboard", color: .purple),
        Subcategory(name: "Loss of Smell", image:"list.clipboard", color: .purple),
        Subcategory(name: "Loss of Taste", image:"list.clipboard", color: .purple),
        Subcategory(name: "Lower Back Pain", image:"list.clipboard", color: .purple),
        Subcategory(name: "Memory Lapse", image:"list.clipboard", color: .purple),
        Subcategory(name: "Mood Changes", image:"list.clipboard", color: .purple),
        Subcategory(name: "Nausea", image:"list.clipboard", color: .purple),
        Subcategory(name: "Night Sweats", image:"list.clipboard", color: .purple),
        Subcategory(name: "Pelvic Pain", image:"list.clipboard", color: .purple),
        Subcategory(name: "Rapid, Pounding or fluttering Hertbeat", image:"list.clipboard", color: .purple),
        Subcategory(name: "Runny Nose", image:"list.clipboard", color: .purple),
        Subcategory(name: "Shortness of Breath", image:"list.clipboard", color: .purple),
        Subcategory(name: "Skipped Heartbeat", image:"list.clipboard", color: .purple),
        Subcategory(name: "Sleep Changes", image:"list.clipboard", color: .purple),
        Subcategory(name: "Sore Throat", image:"list.clipboard", color: .purple),
        Subcategory(name: "Vaginale Dryness", image:"list.clipboard", color: .purple),
        Subcategory(name: "Vomiting", image:"list.clipboard", color: .purple),
        Subcategory(name: "Wheezing", image:"list.clipboard", color: .purple),
          
        Subcategory(name: "Blood Glucose", image:"waveform.path.ecg.rectangle", color: .pink),
        Subcategory(name: "Blood Pressure", image:"waveform.path.ecg.rectangle", color: .pink),
        Subcategory(name: "Body Temperature", image:"waveform.path.ecg.rectangle", color: .pink),
        Subcategory(name: "Heart Rate", image:"waveform.path.ecg.rectangle", color: .pink),
        Subcategory(name: "Respiratory Rate", image:"waveform.path.ecg.rectangle", color: .pink),
        
    ]
}

